version: '3.9'
services:
  ### ===================
  ### DB SERVICE
  ### ===================
  db:
    image: postgres:15.3-alpine3.18
    container_name: postgres_db
    ports: 
    - 5433:5432 
    environment:
      POSTGRES_DB: LoyaltyPointsDB
      POSTGRES_USER: Njoguu
      POSTGRES_PASSWORD: alannjoguu

    restart: always

  # ===========
  # API SERVICE
  # ===========
  api:
    container_name: gin_api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - db
      - cache
        # entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    # command: [ "/app/main" ]
    restart: always

  ### ===================
  ### CACHE SERVICE
  ### ===================
  cache: 
    container_name: redis_cache
    image: redis:7.2-rc2-alpine
    ports:
      - 6380:6379
