version: '3.9'
services:
  ### ===================
  ### DB SERVICE
  ### ===================
  postgres:
    image: postgres:15.3-alpine3.18
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}

  # ===========
  # API SERVICE
  # ===========
  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: [ "/app/main" ]

  ### ===================
  ### CACHE SERVICE
  ### ===================
  redis: 
    image: redis:7.2-rc2-alpine
    ports:
      - 6379:6379
